apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::329321783204:role/eksctl-simple-api-nodegroup-ng-f5-NodeInstanceRole-1PE7ZBVF1I3CJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::329321783204:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-02T09:14:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1422"
  uid: 55e668b3-806b-453b-8636-bdecdde90eea
